# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/thile/Dropbox/School Work/EE 178/Labs/Lab 8/group2_lab8/group2_lab8.srcs/sources_1/ip/framebuffer/framebuffer.xci
# IP: The module: 'framebuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thile/Dropbox/School Work/EE 178/Labs/Lab 8/group2_lab8/group2_lab8.srcs/sources_1/ip/framebuffer/framebuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'framebuffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/thile/Dropbox/School Work/EE 178/Labs/Lab 8/group2_lab8/group2_lab8.srcs/sources_1/ip/framebuffer/framebuffer.xci
# IP: The module: 'framebuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thile/Dropbox/School Work/EE 178/Labs/Lab 8/group2_lab8/group2_lab8.srcs/sources_1/ip/framebuffer/framebuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'framebuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
