# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.cache/wt [current_project]
set_property parent.project_path C:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet c:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.srcs/sources_1/ip/framebuffer/framebuffer.dcp
set_property used_in_implementation false [get_files c:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.srcs/sources_1/ip/framebuffer/framebuffer.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.srcs/sources_1/imports/imports/ee178_fall2016_lab6/linedraw.v
  C:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.srcs/sources_1/imports/imports/ee178_fall2016_lab6/vga_timing.v
  C:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.srcs/sources_1/imports/imports/ee178_fall2016_lab8/vga_example.v
  C:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.srcs/sources_1/imports/imports/ee178_fall2016_lab8/kcpsm6.v
  C:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.srcs/sources_1/imports/imports/ee178_fall2016_lab2/quad_seven_seg.v
  C:/Users/Jacky/test/FPGA_Space_Invaders/software/software.v
  C:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.srcs/sources_1/imports/imports/ee178_fall2016_lab8/project.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.srcs/constrs_1/imports/ee178_fall2016_lab8/project.xdc
set_property used_in_implementation false [get_files C:/Users/Jacky/test/FPGA_Space_Invaders/FPGA_Space_Invaders.srcs/constrs_1/imports/ee178_fall2016_lab8/project.xdc]


synth_design -top project -part xc7a35tcpg236-1


write_checkpoint -force -noxdef project.dcp

catch { report_utilization -file project_utilization_synth.rpt -pb project_utilization_synth.pb }
